---
abstract: 'A Perl interface to the EMBL-EBI RNA-seq analysis API'
author:
  - 'Maria Keays <maria.keays@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.02, CPAN::Meta::Converter version 2.142690'
license: lgpl_3_0
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Bio-EBI-RNAseqAPI
no_index:
  directory:
    - t
    - inc
requires:
  JSON::Parse: '0.32'
  LWP::UserAgent: '6.06'
  Log::Log4perl: '1.46'
  Moose: '2.1402'
  MooseX::FollowPBP: '0.05'
version: '1.03'
release_status: stable
